### PR TITLE
Update event.php

### PR DESCRIPTION
**Pull request by cswiers**
Allow order amount to be retreived, this so the amount can be checked in a later state (for partial payments for example).

### CODE REVIEW

**Comment by danielmcoelho** [comment]
Hello @cswiers, thanks very much for your contribution to our lib 💪 

Can I ask to describe just a bit more what is a partial payment?
Utrust handles the underpayments/overpayments internally, no need for the merchant to check the amount because the amount will always be the Order amount. 
What's your use case to add this checking? 😃

**Comment by cswiers** [comment]
Hello @danielmcoelho,

Thank you for getting back at me.

We allow our customers to make partial payments for our invoices. A customer can choose which paymentmethod they want to use. Different payment methods use different ways to check whether a payment is actually complete. It is important for us to check if the total amount of an invoice is paid in the end and therefore we would like to check the amount that is actually paid by the customer.

Hope this makes our use case a little bit more clear.

Thanks again.

Kind regards,
@cswiers

**Comment by danielmcoelho** [comment]
Thanks @cswiers,

So if I understand correctly, you are creating an Order per partial payment, right? Our event will let you know if that Order is PAID or CANCELLED, the amount that you are getting on the Event is not the amount that the buyer sent but it's the Order amount. So you don't need to check it because it's redundant info for debug purposes –> it's the `Order.amount.total` you send us when creating the order [here](https://github.com/utrustdev/utrust-php/blob/ec798497620bc86548dbf95d85d8876975a25138/examples/create_simple_order.php#L19).
Does this make sense?

Sorry, I'm also trying to understand if we can improve in the documentation, for sure we can.

**Comment by cswiers** [comment]
Hi @danielmcoelho ,

Yes, you understand me correctly. The documentation is clear on the way the order is processed, and what you're saying does make sense. 

The problem for us however is that we use multiple payment gateways of which some of them do require us to check the amount. With Paypal for example it is possible to alter the order amount after the visitor leaves our website in some situations and therefor needs to be checked when the payment notification webhook is called. 

What we would like to accomplish here is the ability to communicate with all the different gateways we support as similar as possible. This library for the UTrust payment gateway is the only one which did not send back the paid amount by default and therefore I added it and send this pull request.

Kind regards,
@cswiers

**Comment by danielmcoelho** [comment]
Hey @cswiers ,

Thanks for the explanation. I see no harm in adding this so I'll squash and merge, I just wanted to understand your point of view, thanks!

**Comment by cswiers** [comment]
Thank you too!

**Pull request merged**
